### ISSUE TITLE
API endpoint for CNN and tribunnews are same

### ISSUE THREAD

**Issue by Fikriihsan03** [bagusindrayana/scraping-berita#2]
![Screenshot from 2022-09-29 16-49-23](https://user-images.githubusercontent.com/64629006/193000458-f769b58e-8fe9-48fd-96c9-b52186e7ea0b.png)

**Comment by bagusindrayana** [comment]
https://github.com/bagusindrayana/scraping-berita/commit/c76ae006c439a2eb852087f6779df9f935b88500
